2018-03-16 09:17:36,285 ERROR 12988 [-/undefined/-/270788ms POST /party] nodejs.ECONNABORTEDError: write ECONNABORTED
    at _errnoException (util.js:1024:11)
    at Socket._writeGeneric (net.js:767:25)
    at Socket._write (net.js:786:8)
    at doWrite (_stream_writable.js:387:12)
    at clearBuffer (_stream_writable.js:514:7)
    at Socket.Writable.uncork (_stream_writable.js:313:7)
    at ServerResponse.end (_http_outgoing.js:774:21)
    at Object.respond (E:\JS\pass3\node_modules\koa\lib\application.js:232:7)
    at handleResponse (E:\JS\pass3\node_modules\koa\lib\application.js:137:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
code: 'ECONNABORTED'
errno: 'ECONNABORTED'
syscall: 'write'
headerSent: true
name: 'ECONNABORTEDError'
pid: 12988
hostname: USER-GALVAKJA59

2018-03-16 09:17:36,283 ERROR 8716 nodejs.ClusterClientNoResponseError: client no response in 290892ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\pass3\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 8716
hostname: USER-GALVAKJA59

2018-03-16 09:17:36,288 ERROR 12988 nodejs.ServerNoResponseError: server 127.0.0.1:55403 no response in 20001ms, maybe the socket is end on the other side. (address: 127.0.0.1:55403)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\pass3\node_modules\tcp-base\lib\base.js:427:21)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ServerNoResponseError'
pid: 12988
hostname: USER-GALVAKJA59

2018-03-17 10:41:03,581 ERROR 396 [egg-mongoose] mongodb://10.50.1.250:27017/test disconnected
2018-03-17 10:41:03,596 ERROR 396 nodejs.MongoError: [egg-mongoose]failed to connect to server [10.50.1.250:27017] on first connect [MongoError: connect ETIMEDOUT 10.50.1.250:27017]
    at Pool.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
name: 'MongoError'
message: '[egg-mongoose]failed to connect to server [10.50.1.250:27017] on first connect [MongoError: connect ETIMEDOUT 10.50.1.250:27017]'
pid: 396
hostname: ghm-pc

2018-03-17 10:50:41,409 ERROR 396 agent still doesn't ready after 600000 ms.
2018-03-17 23:56:34,606 ERROR 10708 nodejs.ClusterClientNoResponseError: client no response in 3149128ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\JS\pass3\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 10708
hostname: ghm-pc

